### ISSUE TITLE
Links with `data-remote=true` do not use the normal "open link in new tab" behavior when command/control + clicked

### ISSUE THREAD

**Issue by tcannonfodder** [KonnorRogers/mrujs#216]
#### Expected Behaviour

When a link has the `data-remote` tag, using the keyboard shortcut to open a link in a new tab silently fails.

#### Actual Behaviour

A link should one openable in a new tab; with the `data-remote` acting as a sprinkle of interactivity; or there should be a way to opt into that behavior.

#### Steps to Reproduce

See the following codepen for a minimal example: https://codepen.io/tcannonfodder/full/abgZeWP

**Comment by tcannonfodder** [comment]
I hate to be the bearer of bad news, but it still looks like this error is occurring; both in my app and in the CodePen (which is running `1.0.1`)

**Comment by KonnorRogers** [comment]
🤔 let me take another look.
